
export type FemaleProfile = {
  name: string;
  age: number;
  distance: number;
  description: string;
  imageUrl: string;
  imageHint: string;
};

export const femaleProfiles: FemaleProfile[] = [
  {
    name: 'Thais silva',
    age: 26,
    distance: 9,
    description: 'Amo servir na igreja e cozinhar. Busco alguém que compartilhe minha fé e sonhe em construir uma família abençoada.',
    imageUrl: 'https://i.pinimg.com/736x/bd/e4/29/bde4292c78705160f5a14f14e63d2a16.jpg',
    imageHint: 'woman portrait',
  },
  {
    name: 'Beatriz',
    age: 29,
    distance: 1.5,
    description: 'Professora cristã, apaixonada por música gospel e crianças. Creio que Deus tem planos perfeitos para nossa vida.',
    imageUrl: 'https://i.imgur.com/3qV0WxN.jpeg',
    imageHint: 'woman smiling',
  },
  {
    name: 'Camila',
    age: 24,
    distance: 3,
    description: 'Enfermeira dedicada. Acredito que Deus tem planos perfeitos para nós e busco um companheiro de fé.',
    imageUrl: 'https://i.imgur.com/3qV0WxN.jpeg',
    imageHint: 'woman outside',
  },
  {
    name: 'Débora',
    age: 31,
    distance: 4,
    description: 'Líder de louvor, amo adorar a Deus e busco um companheiro que me ajude a crescer na fé e no amor.',
    imageUrl: 'https://i.imgur.com/MtlGkxm.jpeg',
    imageHint: 'woman singing',
  },
  {
    name: 'Esther',
    age: 27,
    distance: 2.8,
    description: 'Psicóloga e cristã. Quero construir uma família nos caminhos do Senhor e servir ao próximo com amor.',
    imageUrl: 'https://i.imgur.com/FutqOA0.jpeg',
    imageHint: 'woman in office',
  },
  {
    name: 'Fernanda',
    age: 25,
    distance: 3.2,
    description: 'Pedagoga apaixonada por crianças e pelo ministério infantil. Busco um relacionamento baseado na Palavra.',
    imageUrl: 'https://i.imgur.com/VSmG9VZ.jpeg',
    imageHint: 'woman with children',
  },
  {
    name: 'Gabriela',
    age: 33,
    distance: 1.8,
    description: 'Empresária e mulher de fé, quero dividir minha jornada com alguém que sonha grande com Deus.',
    imageUrl: 'https://i.imgur.com/UReFecv.jpeg',
    imageHint: 'business woman',
  },
  {
    name: 'Helena',
    age: 28,
    distance: 2.5,
    description: 'Missionária e enfermeira. Amo servir ao próximo e sonho em construir um lar cristão cheio de amor.',
    imageUrl: 'https://i.imgur.com/5IVW3H3.jpeg',
    imageHint: 'woman in scrubs',
  },
  {
    name: 'Isadora',
    age: 30,
    distance: 3.7,
    description: 'Advogada e líder de mulheres na igreja. Busco um homem que me lidere no amor e na fé.',
    imageUrl: 'https://i.imgur.com/AnMx85m.jpeg',
    imageHint: 'woman in suit',
  },
  {
    name: 'Júlia',
    age: 25,
    distance: 2.1,
    description: 'Fisioterapeuta e ministra de dança. Amo expressar minha adoração através da arte e busco um companheiro de fé.',
    imageUrl: 'https://i.imgur.com/PBIFO20.jpeg',
    imageHint: 'woman dancing',
  },
  {
    name: 'Amanda',
    age: 59,
    distance: 2.1,
    description: 'Aposentada e amante da leitura bíblica e serva ativa na igreja. Procuro um relacionamento fundamentado em oração e verdade.',
    imageUrl: 'https://i.imgur.com/fij2Ogc.jpeg',
    imageHint: 'older woman reading bible',
  },
  {
    name: 'Yara',
    age: 65,
    distance: 2.9,
    description: 'Missionária aposentada, creio que Deus guia nossos passos e planos.',
    imageUrl: 'https://i.imgur.com/qmU5fVB.jpeg',
    imageHint: 'older woman smiling',
  },
  {
    name: 'Cris',
    age: 26,
    distance: 6.1,
    description: 'Estudante de teologia e apaixonada por missões. Oro por um homem que caminhe comigo em fé e propósito.',
    imageUrl: 'https://i.imgur.com/Gg6vv6i.jpeg',
    imageHint: 'young woman with books',
  },
  {
    name: 'Valéria',
    age: 59,
    distance: 2.8,
    description: 'Aposentada e ministra de louvor, busco alguém para compartilhar a fé e o amor de Deus.',
    imageUrl: 'https://i.imgur.com/MXDoepb.jpeg',
    imageHint: 'older woman singing',
  },
  {
    name: 'Daniela',
    age: 25,
    distance: 2.5,
    description: 'Professora e líder de jovens, busco alguém para compartilhar fé, sonhos e uma vida com propósito.',
    imageUrl: 'https://i.imgur.com/CNwwPOr.jpeg',
    imageHint: 'woman with young people',
  },
  {
    name: 'Joana',
    age: 37,
    distance: 2.4,
    description: 'Líder de ministério e esposa dedicada, acredito que Deus tem um plano para cada coração.',
    imageUrl: 'https://picsum.photos/seed/fp1/200/200',
    imageHint: 'woman praying',
  },
  {
    name: 'Xênia',
    age: 63,
    distance: 2.5,
    description: 'Voluntária da igreja, acredito que o amor de Deus é eterno e sempre renovado.',
    imageUrl: 'https://picsum.photos/seed/fp2/200/200',
    imageHint: 'older woman at church',
  },
  {
    name: 'Larissa',
    age: 41,
    distance: 3.0,
    description: 'Pedagoga e ministra de louvor, acredito que o amor de Deus transforma vidas e corações.',
    imageUrl: 'https://picsum.photos/seed/fp3/200/200',
    imageHint: 'woman with microphone',
  },
  {
    name: 'Bruna',
    age: 21,
    distance: 3.2,
    description: 'Apaixonada por música gospel e ministério de louvor. Quero construir uma família com propósito.',
    imageUrl: 'https://picsum.photos/seed/fp4/200/200',
    imageHint: 'young woman singing',
  },
  {
    name: 'Olívia',
    age: 47,
    distance: 3.4,
    description: 'Voluntária e ministra de oração, acredito no poder da fé para transformar corações.',
    imageUrl: 'https://picsum.photos/seed/fp5/200/200',
    imageHint: 'woman praying in group',
  },
  {
    name: 'Zilda',
    age: 67,
    distance: 3.0,
    description: 'Ensinar a Palavra é minha missão. Acredito no amor que cresce com fé e compromisso.',
    imageUrl: 'https://picsum.photos/seed/fp6/200/200',
    imageHint: 'older woman teaching',
  },
  {
    name: 'Tatiana',
    age: 55,
    distance: 3.7,
    description: 'Ensinando a Bíblia há anos, sigo acreditando que o amor em Deus é o mais duradouro.',
    imageUrl: 'https://picsum.photos/seed/fp7/200/200',
    imageHint: 'woman with bible',
  },
  {
    name: 'Carla',
    age: 23,
    distance: 1.8,
    description: 'Enfermeira que ama servir ao próximo. Acredito que Deus tem um plano perfeito para nossa vida.',
    imageUrl: 'https://picsum.photos/seed/fp8/200/200',
    imageHint: 'nurse smiling',
  },
  {
    name: 'Wanda',
    age: 61,
    distance: 3.1,
    description: 'Amo servir na igreja e acredito que nunca é tarde para um novo começo com Deus.',
    imageUrl: 'https://picsum.photos/seed/fp9/200/200',
    imageHint: 'older woman at church event',
  },
  {
    name: 'Sônia',
    age: 53,
    distance: 2.1,
    description: 'Pastora aposentada e ministra de louvor, acredito na força da oração e do amor verdadeiro.',
    imageUrl: 'https://picsum.photos/seed/fp10/200/200',
    imageHint: 'woman leading worship',
  },
  {
    name: 'Elisa',
    age: 27,
    distance: 2.9,
    description: 'Advogada cristã, acredito que o amor verdadeiro é fruto da fé e do compromisso sincero.',
    imageUrl: 'https://picsum.photos/seed/fp11/200/200',
    imageHint: 'woman in courtroom',
  },
  {
    name: 'Patrícia',
    age: 49,
    distance: 2.9,
    description: 'Educadora e conselheira espiritual, busco um amor fundamentado na palavra de Deus.',
    imageUrl: 'https://picsum.photos/seed/fp12/200/200',
    imageHint: 'woman counseling',
  },
  {
    name: 'Rafaela',
    age: 51,
    distance: 3.3,
    description: 'Missionária e professora, creio que o amor de Deus nunca envelhece.',
    imageUrl: 'https://picsum.photos/seed/fp13/200/200',
    imageHint: 'woman in classroom',
  },
  {
    name: 'Mariana',
    age: 43,
    distance: 2.6,
    description: 'Pastora e conselheira espiritual, busco um companheiro para uma caminhada de fé e amor.',
    imageUrl: 'https://picsum.photos/seed/fp14/200/200',
    imageHint: 'woman giving sermon',
  },
  {
    name: 'Gisele',
    age: 31,
    distance: 1.9,
    description: 'Psicóloga que acredita no poder da oração e do amor para transformar vidas.',
    imageUrl: 'https://picsum.photos/seed/fp15/200/200',
    imageHint: 'psychologist office',
  },
  {
    name: 'Fabiana',
    age: 29,
    distance: 3.3,
    description: 'Missionária e voluntária, sonho em construir uma família fundamentada em Deus e no amor.',
    imageUrl: 'https://picsum.photos/seed/fp16/200/200',
    imageHint: 'woman doing charity work',
  },
  {
    name: 'Isabel',
    age: 35,
    distance: 3.1,
    description: 'Professora apaixonada por educação cristã. Busco um parceiro para caminhar na fé e no amor.',
    imageUrl: 'https://picsum.photos/seed/fp17/200/200',
    imageHint: 'teacher in sunday school',
  },
  {
    name: 'Heloísa',
    age: 33,
    distance: 2.7,
    description: 'Empresária e adoradora. Creio que os planos de Deus superam nossas expectativas humanas.',
    imageUrl: 'https://picsum.photos/seed/fp18/200/200',
    imageHint: 'business woman praying',
  },
  {
    name: 'Natália',
    age: 45,
    distance: 4.2,
    description: 'Empreendedora cristã com sede de propósito. Espero encontrar um parceiro que valorize a presença de Deus no relacionamento.',
    imageUrl: 'https://picsum.photos/seed/fp19/200/200',
    imageHint: 'woman in her shop',
  },
];
