
export type MaleProfile = {
  name: string;
  age: number;
  distance: number;
  description: string;
  imageUrl: string;
  imageHint: string;
};

export const maleProfiles: MaleProfile[] = [
  {
    name: 'Fernando',
    age: 34,
    distance: 12,
    description: 'Pastor jovem, apaixonado por evangelizar e servir a comunidade. Busco uma companheira que ame a Deus.',
    imageUrl: 'https://i.pinimg.com/736x/db/51/10/db5110fd60f5749bfa445f2f027651c9.jpg',
    imageHint: 'man portrait',
  },
  {
    name: 'Bruno',
    age: 28,
    distance: 2.3,
    description: 'Engenheiro e diácono. Busco uma mulher que ame a Deus acima de tudo e queira construir uma família cristã.',
    imageUrl: 'https://i.imgur.com/FcUW0qR.jpeg',
    imageHint: 'man smiling',
  },
  {
    name: 'Carlos',
    age: 32,
    distance: 3.5,
    description: 'Empresário cristão. Creio que Deus preparou alguém especial para mim e busco relacionamento com propósito.',
    imageUrl: 'https://i.imgur.com/PbZoBM1.jpeg',
    imageHint: 'man outside',
  },
  {
    name: 'Daniel',
    age: 26,
    distance: 1.2,
    description: 'Músico da igreja e professor. Sonho em formar uma família abençoada baseada nos valores cristãos.',
    imageUrl: 'https://i.imgur.com/B2JIUFq.jpeg',
    imageHint: 'man playing guitar',
  },
  {
    name: 'Eduardo',
    age: 29,
    distance: 4.2,
    description: 'Médico dedicado. Quero encontrar minha companheira de vida e fé para servirmos juntos ao Senhor.',
    imageUrl: 'https://i.imgur.com/LM1fzrM.jpeg',
    imageHint: 'man in scrubs',
  },
  {
    name: 'Felipe',
    age: 31,
    distance: 2.7,
    description: 'Advogado e líder jovem. Busco uma mulher temente a Deus para construirmos juntos o que Ele preparou.',
    imageUrl: 'https://i.imgur.com/ej5w0hd.jpeg',
    imageHint: 'man in suit',
  },
    {
    name: 'Gabriel',
    age: 27,
    distance: 3.8,
    description: 'Contador e ministro de louvor. Acredito que Deus tem uma pessoa especial preparada para cada um de nós.',
    imageUrl: 'https://i.imgur.com/DDLNBtA.jpeg',
    imageHint: 'man singing',
  },
  {
    name: 'Henrique',
    age: 34,
    distance: 1.9,
    description: 'Professor universitário e pregador. Busco uma companheira que compartilhe do amor por Jesus e pela família.',
    imageUrl: 'https://i.imgur.com/H27Kbc9.jpeg',
    imageHint: 'man with books',
  },
  {
    name: 'Igor',
    age: 29,
    distance: 2.4,
    description: 'Arquiteto e líder de célula. Quero construir não só prédios, mas também um lar cristão ao lado de uma mulher especial.',
    imageUrl: 'https://i.imgur.com/HPs3Xhv.jpeg',
    imageHint: 'man with blueprints',
  },
  {
    name: 'João',
    age: 33,
    distance: 3.1,
    description: 'Dentista e missionário nas horas vagas. Busco uma companheira para servir juntos no Reino de Deus.',
    imageUrl: 'https://i.imgur.com/03yYaAh.jpeg',
    imageHint: 'man smiling portrait',
  },
  {
    name: 'Lucas',
    age: 37,
    distance: 2.0,
    description: 'Administrador e diácono. Acredito que o amor começa com propósito em Deus.',
    imageUrl: 'https://i.imgur.com/0MllOil.jpeg',
    imageHint: 'man in office',
  },
  {
    name: 'Marcelo',
    age: 39,
    distance: 3.4,
    description: 'Engenheiro civil e voluntário na igreja. Busco uma parceira para caminhar com fé.',
    imageUrl: 'https://picsum.photos/seed/mp12/200/200',
    imageHint: 'man with hard hat',
  },
  {
    name: 'Natan',
    age: 41,
    distance: 2.9,
    description: 'Empresário cristão, fiel a Deus e à família. Acredito em um amor maduro e verdadeiro.',
    imageUrl: 'https://picsum.photos/seed/mp13/200/200',
    imageHint: 'older man portrait',
  },
  {
    name: 'Otávio',
    age: 44,
    distance: 3.7,
    description: 'Pastor auxiliar. Quero alguém para edificar juntos uma família nos caminhos do Senhor.',
    imageUrl: 'https://picsum.photos/seed/mp14/200/200',
    imageHint: 'older man smiling',
  },
  {
    name: 'Paulo',
    age: 47,
    distance: 2.3,
    description: 'Missionário experiente e conselheiro cristão. Procuro uma mulher com propósito.',
    imageUrl: 'https://picsum.photos/seed/mp15/200/200',
    imageHint: 'man reading bible',
  },
  {
    name: 'Rafael',
    age: 50,
    distance: 3.6,
    description: 'Professor e líder de intercessão. Quero amar e servir com alguém que também ama Jesus.',
    imageUrl: 'https://picsum.photos/seed/mp16/200/200',
    imageHint: 'man praying',
  },
  {
    name: 'Samuel',
    age: 53,
    distance: 2.8,
    description: 'Aposentado, mas ainda ativo na igreja. Creio que nunca é tarde para um novo amor com Deus.',
    imageUrl: 'https://picsum.photos/seed/mp17/200/200',
    imageHint: 'senior man smiling',
  },
  {
    name: 'Thiago',
    age: 56,
    distance: 3.2,
    description: 'Ministro de louvor e escritor cristão. Busco alguém para dividir a vida e a fé.',
    imageUrl: 'https://picsum.photos/seed/mp18/200/200',
    imageHint: 'man writing',
  },
  {
    name: 'Ubiratan',
    age: 59,
    distance: 1.7,
    description: 'Missionário aposentado, ainda com muito amor a oferecer. Sonho em recomeçar ao lado de alguém de fé.',
    imageUrl: 'https://picsum.photos/seed/mp19/200/200',
    imageHint: 'senior man outside',
  },
  {
    name: 'Valmir',
    age: 62,
    distance: 2.1,
    description: 'Líder de oração e intercessão. Quero alguém para viver os melhores anos com propósito.',
    imageUrl: 'https://picsum.photos/seed/mp20/200/200',
    imageHint: 'senior man praying',
  },
  {
    name: 'Washington',
    age: 65,
    distance: 3.0,
    description: 'Amo a palavra, a igreja e ainda tenho muitos planos em Deus para realizar com alguém especial.',
    imageUrl: 'https://picsum.photos/seed/mp21/200/200',
    imageHint: 'elderly man smiling',
  },
  {
    name: 'Xavier',
    age: 67,
    distance: 2.6,
    description: 'Sábio e cheio de fé. Acredito que o amor verdadeiro é guiado pela obediência a Deus.',
    imageUrl: 'https://picsum.photos/seed/mp22/200/200',
    imageHint: 'elderly man reading',
  },
];
